name: test cron

on:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  hello:
    runs-on: ubuntu-latest
    name: test cron
    strategy:
      matrix:
        domain:
          - https://caiyunapp.com
          - https://www.colorfulclouds.com
    steps:
      - name: Trigger
        run: echo `date`
